parameters:
  simulator.base_url: '%env(string:SIMULATOR_BASE_URL)%'

services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'

  App\Controller\:
    resource: '../src/Controller/'
    public: true
    tags: ['controller.service_arguments']

  App\Service\SimulatorClient:
    arguments:
      $baseUrl: '%simulator.base_url%'
