# config/services.yaml
parameters: { }

services:
  # Valeurs par défaut pour tous les services
  _defaults:
    autowire: true      # Injecte automatiquement les dépendances des services
    autoconfigure: true # Enregistre automatiquement les tags adéquats

  # Enregistre tous les services de src/ (sauf exceptions ci-dessous)
  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'

  # (Optionnel) Import spécifique des contrôleurs avec le tag controller.service_arguments
  App\Controller\:
    resource: '../src/Controller/'
    tags: ['controller.service_arguments']

  # ---- Configuration explicite du SimulatorClient ----
  App\Service\SimulatorClient:
    arguments:
      $baseUrl: '%env(resolve:SIMULATOR_BASE_URL)%'
      # Si ton constructeur a aussi une $apiKey :
      # $apiKey: '%env(SIMULATOR_API_KEY)%'
