# config/packages/nelmio_cors.yaml
nelmio_cors:
  defaults:
    origin_regex: true
    allow_origin: ['^http://localhost:[0-9]+$']
    allow_credentials: true
    allow_headers: ['Content-Type','Authorization','Accept','Origin','X-Requested-With']
    allow_methods: ['GET','POST','PUT','PATCH','DELETE','OPTIONS']
    max_age: 3600
    hosts: []
  paths:
    '^/api/': ~
