security:
  password_hashers:
    App\Entity\User: 'auto'

  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    api:
      pattern: ^/api
      stateless: true
      provider: app_user_provider
      jwt: ~   # Protège /api/* par token, sauf exceptions access_control

  access_control:
    - { path: ^/api/auth, roles: PUBLIC_ACCESS }
    - { path: ^/api/simulations, roles: IS_AUTHENTICATED_FULLY }
    - { path: ^/api/clients, roles: IS_AUTHENTICATED_FULLY }
